// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelematicsPipeline.Api.Persistence;

#nullable disable

namespace TelematicsPipeline.Api.Migrations
{
    [DbContext(typeof(TelematicsDbContext))]
    partial class TelematicsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelematicsPipeline.Api.Models.TelematicsRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AccelerationXG")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "accelerationXG");

                    b.Property<double?>("AccelerationYG")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "accelerationYG");

                    b.Property<double?>("AccelerationZG")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "accelerationZG");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "deviceId");

                    b.Property<double?>("EngineCoolantTempC")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "engineCoolantTempC");

                    b.Property<int?>("EngineRpm")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "engineRpm");

                    b.Property<double?>("FuelLevelPercent")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "fuelLevelPercent");

                    b.Property<double>("HeadingDegrees")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "headingDegrees");

                    b.Property<bool>("IsIdling")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isIdling");

                    b.Property<bool>("IsIgnitionOn")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isIgnitionOn");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "longitude");

                    b.Property<double>("OdometerKm")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "odometerKm");

                    b.Property<double>("SpeedKmh")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "speedKmh");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.ToTable("TelematicsRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
